---
# Handlers for monitoring_hub role

- name: restart grafana
  ansible.builtin.systemd:
    name: "{{ monitoring_services[0] }}"
    state: restarted
    daemon_reload: yes

- name: restart influxdb
  ansible.builtin.systemd:
    name: "{{ monitoring_services[1] }}"
    state: restarted
    daemon_reload: yes
  async: 30
  poll: 2