services:
  hayek_solana_pentest:
    image: hayek-solana-pentest:latest
    container_name: hayek-solana-pentest
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    working_dir: /pentest
    restart: unless-stopped
    volumes:
      - ${HOME}/hayek-pentest:/root/pentest/results
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/go/bin
    # Optimizaciones de red para pentest
    network_mode: bridge
    cap_add:
      - NET_RAW
      - NET_ADMIN